include = ["Cargo.toml", "crates/*/*.toml"]

[formatting]
align_entries = true
allowed_blank_lines = 1
column_width = 120
reorder_arrays = true
reorder_keys = true

[[rule]]
formatting = { reorder_arrays = false, reorder_keys = false }
keys = ["package"]
