[workspace]
members  = ["crates/*"]
resolver = "2"

[workspace.dependencies]
html5ever = "0.27.0"
indexmap  = "2.2.6"
kuchikiki = { git = "https://github.com/xusd320/kuchikiki.git", rev = "f1b69c1" }

[profile.release]
lto   = true
strip = "symbols"
