/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parse(html: string): ElementRef
export declare class ElementRef {
  querySelector(selectors: string): ElementRef | null
  querySelectorAll(selectors: string): Array<ElementRef>
  getAttribute(name: string): string | null
  getAllAttributes(): object | null
  outerHtml(): string
  innerHtml(): string
}
