/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parse(html: string): NodeRepr
export declare class NodeRepr {
  append(newChild: NodeRepr): void
  appendSequence(newChildren: Array<NodeRepr>): void
  prepend(newChild: NodeRepr): void
  prependSequence(newChildren: Array<NodeRepr>): void
  insertAfter(newSibling: NodeRepr): void
  insertSequenceAfter(newSiblings: Array<NodeRepr>): void
  insertBefore(newSibling: NodeRepr): void
  insertSequenceBefore(newSiblings: Array<NodeRepr>): void
  remove(): void
  setAttribute(name: string, value: string): void
  setAttributes(attrs: Record<string, string>): void
  removeAttribute(name: string): void
  removeAllAttributes(): void
  select(selectors: string): NodeRepr | null
  selectAll(selectors: string): Array<NodeRepr>
  getChildren(): Array<NodeRepr>
  getAttribute(name: string): string | null
  getAttributes(): Record<string, string>
  outerHtml(): string
  innerHtml(): string
  text(): string
  clone(): NodeRepr
  cloneRecursive(): NodeRepr
}
